version: '3'
services:
######################################
# PHP-FPM Container
######################################
  php-fpm:
    container_name: php-fpm
    image: petronetto/php7-alpine
    environment:
      XDEBUG_ENABLE: 1
      XDEBUG_HOST: ${MY_IP} # .env
      XDEBUG_REMOTE_PORT: 9000
      NEWRELIC_ENABLED: 0
      NEWRELIC_LICENSE: ""
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    links:
      - database
    volumes:
      - ./example:/app
######################################
# NGINX Container
######################################
  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - php-fpm
    volumes:
      - ./example:/app
    ports:
      - 8080:8080
######################################
# Caddy Container
######################################
  caddy:
    container_name: caddy
    build: ./caddy
    links:
      - php-fpm
    volumes:
      - ./example:/app
    ports:
      - 8000:8080
######################################
# Database Container
######################################
  database:
    container_name: database
    restart: always
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql
