version: '3'
services:
######################################
# PHP-FPM Container
######################################
  php-fpm:
    container_name: php-fpm
    network_mode: bridge
    build: php-fpm
    environment:
      XDEBUG_HOST: ${MY_IP} # .env
      XDEBUG_REMOTE_PORT: 9000
    volumes:
      - ./example:/app
######################################
# Caddy Container
######################################
  caddy:
    container_name: caddy
    network_mode: bridge
    build: ./caddy
    links:
      - php-fpm
    volumes:
      - ./example:/app
    ports:
      - 8080:8080
######################################
# NGINX Container
######################################
  nginx:
    container_name: nginx
    network_mode: bridge
    build: ./nginx
    links:
      - php-fpm
    volumes:
      - ./example:/app
    ports:
      - 9000:8080