version: '3'
services:
######################################
# PHP-FPM Container
######################################
  php-fpm:
    container_name: php-fpm
    image: petronetto/php7-alpine
    environment:
      XDEBUG_ENABLE: 1
      XDEBUG_HOST: ${MY_IP} # .env
      XDEBUG_REMOTE_PORT: 9000
      NEWRELIC_ENABLED: 1
      NEWRELIC_LICENSE: "01be7a2ce288ca021303ce2e7aad11d5f8294105"
    volumes:
      - ./example:/app
######################################
# NGINX Container
######################################
  nginx:
    container_name: nginx
    build: ./nginx
    links:
      - php-fpm
    volumes:
      - ./example:/app
    ports:
      - 8080:8080
######################################
# Caddy Container
######################################
  caddy:
    container_name: caddy
    build: ./caddy
    links:
      - php-fpm
    volumes:
      - ./example:/app
    ports:
      - 8000:8080
